spring.application.name=first_simple_project
spring.datasource.url= jdbc:mysql://localhost:3306/testdb
spring.datasource.usernamename=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true